version: "3.9"
services:
  neighbr:
    env_file: .env
    environment:
      - PORT
      - NODE_ENV
      - DB_URI
      - MAPBOX_API_KEY
      - jwtSecret
    build: .
    ports:
      - 51234:51234

  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/mongodb/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  nginx:
    depends_on:
      - neighbr
      # - mongo
    restart: always
    volumes:
      - type: bind
        source: /var/log/nginx
        target: /var/log/nginx
      - type: bind
        source: /etc/letsencrypt/archive/neighbr.site
        target: /etc/nginx/certs

    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=neighbr.site
      - NGINX_PORT=80
