version: "3.9"
services:
  neighbr:
    env_file: .env
    environment:
      - PORT
      - NODE_ENV
      - DB_URI
      - MAPBOX_API_KEY
      - jwtSecret
    build: .
    # ports:
    #   - 3000:3000
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/mongodb/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  nginx:
    depends_on:
      - neighbr
      - mongo
    restart: always
    volumes:
      - /var/log/nginx:/var/log/nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=neighbr.site
      - NGINX_PORT=80
