version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/mongodb/database:/data/db
    ports: 
      - 51234:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD