version: 2.1
# orbs:
#   node: circleci/node@5.0
# workflows:
#   test:
#     jobs:
#       - node/test:
          # test-results-for: jest
jobs:
  test:
    working_directory: ~/neighbr
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
          # npm ci is the npm install for container environments
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm run test
      - store_artifacts:
          path: coverage

  # deploy:
  #   working_directory: ~/neighbr
  #   docker:
  #     - image: cimg/node:14.19.0
  #   steps:
  #     - checkout
  #     - restore_cache:
